log:
  level: "info"
  path: "logs/error.log"

knock:
  mode: static # static or totp
  static:
    - 9999
    - 9998
    - 9997
  totp:
    secret: "secret"
    prefix: "999"
  skipLoopback: true

door:
  type: "routeros"
  routeros:
    endpoint: "http://10.0.0.1"
    username: "admin"
    password: ""
    addressListName: "OPEN_DOOR"
